### ISSUE TITLE
magento2.1への対応状況について

### ISSUE THREAD

**Issue by nakanek** [Magento-Japan/m2-japaneselocale#14]
はじめまして。
こちらのエクステンションですが、magento2.1は未対応との認識でよろしいでしょうか？

magento2.1をインストールした環境にて

```
composer require magento-japan/m2-japaneselocale:dev-master
```

を実行してみましたが、magento2.1の場合は`magento/framework[100.1.0]`の為エラーとなってしまいます。

そこで、

https://github.com/Magento-Japan/m2-japaneselocale/blob/master/composer.json#L27

を

```
  "require": {
    "magento/framework": "100.*"
  },
```

とすることで解決しそうな気もしますがあまり自信がありませんので、ご確認させて頂きました。
お手数をおかけしますが、よろしくお願いします。

**Comment by nakanek** [comment]
composer.jsonの修正ですが、

```
  "require": {
    "magento/framework": "100.0.*|100.1.*"
  },
```

の方が良いですね。

**Comment by HirokazuNishi** [comment]
諸々の事情で、
https://github.com/HirokazuNishi/m2-japaneselocale
でメンテしてるんですよね・・・（ほぼ大人の事情ですが）

**Comment by nakanek** [comment]
ご返信ありがとうございます。
そもそもの質問なのですが、
こちらのリポジトリ（ https://github.com/Magento-Japan/m2-japaneselocale ）
と
https://github.com/Magento-Japan/m2-jplocalize
の違いってなんでしょうか？

composer.jsonを見る限り、m2-jplocalizeの方だとmagento2.1にも対応しているようですが、
magento2.1のサイト全体を日本語化対応させたい場合、
https://github.com/HirokazuNishi/m2-japaneselocale
とどちらを利用すべきなのでしょうか？

**Comment by HirokazuNishi** [comment]
jplocalizeはフリガナや都道府県のデータ追加、端数処理の修正などをやってます。
japaneselocaleは単にロケールだけです。

日本語で表示ができたら良い、というひとは非日本語圏にたくさんいます。
日本の市場的に日本のマーチャント・ユーザーが納得するようなレベルのローカライズ、となるとこれまたぜんぜん違う話だというのが私の考えです。

本当であればフリガナ、都道府県、端数処理、フォームの項目順など個別にパッケージ化すべきなのですが、現段階ではやっていません。

**Comment by nakanek** [comment]
ご回答ありがとうございます。

日本での国内販売のみを目的としてmagentoを利用したい場合はjplocalizeを、
多言語対応した形での販売を目的としてmagentoを利用したい場合はjapaneselocaleを
利用するといったイメージですかね。

**Comment by HirokazuNishi** [comment]
いえ、jplocalizeには日本語ロケール入ってないです。
それと、jplocalizeは日本国内だけをターゲットにしているわけではなく、日本円・日本市場もターゲットにしたサイトを作ることを想定しています。
jplocalizeはまだベータ版の位置づけなので、大きく実装を変えることもありえます。

**Comment by nakanek** [comment]
そうすると、
日本語表記、日本円・日本市場もターゲットにしたサイトを作りたい場合は、japaneselocaleとjplocalizeを利用し、日本語表記のみでよい場合はjapaneselocaleを利用すると言うことですね。

**Comment by nakanek** [comment]
その後、japaneselocaleをインストールしようと

```
composer require veriteworks/m2-japaneselocale:1.0.4
```

を実行してみましたが、

```
  [Composer\Downloader\TransportException]
  The "https://repo.magento.com/archives/veriteworks/m2-japaneselocale/veriteworks-m2-japaneselocale-1.0.4.0.zip" file could not be downloaded (HTTP/1.1 500 Internal Server Error)
```

といったエラーが発生するようです。
これは実行するコマンドに誤りがあるのでしょうか？

**Comment by HirokazuNishi** [comment]
marketplaceは現在審査中です。審査に非常に時間がかかるので、Gitが更新されたからといってmarketplaceが更新されるとは限りません。

**Comment by HirokazuNishi** [comment]
ああ、1.0.4もうMarketing Review終わってましたね。
そもそも手順が違います。
repo.magento.comはmarketplaceで購入したものか、M2本体専用です。
GithubやBitbucket等とは一切関係ないです。

**Comment by nakanek** [comment]
ご回答ありがとうございます。
この辺をあまり理解しておらず申し訳ないのですが、
```
composer require magento-japan/m2-jplocalize:dev-master
```

が実行できたことから、Magento-Japan/m2-japaneselocaleについても
composer.jsonを修正して頂ければインストール可能なのでしょうか？

その場合、composer.jsonを修正したプルリクを作成したら取り込んで頂けますか？

**Comment by HirokazuNishi** [comment]
このリポジトリは最近メンテナンスしてないので、ここで言われてもほぼ放置です。
そのうちpackagistも整理予定です。

**Comment by nakanek** [comment]
ご回答ありがとうございます。
それでは現時点でmagento2.1の日本語化を行いたい場合は、japaneselocaleのフォークリポジトリを
自分でpackagistに登録するなりしないと実現できないという認識であっていますか？

**Comment by HirokazuNishi** [comment]
そんな必要ないです。
marketplaceで2.1対応のロケール出してますし、composer自体、packagist未登録のものでも利用できる機能がついています。

多分私が何を説明してもあなたには正しく伝わらないと思います。
